
name: test-env

on:
  push:
  workflow_dispatch:

env:
  testSecret: ${{ secrets.SECRET_ONE }}
  DISPLAY_SECRET: ${{ secrets.DISPLAY_SECRET }}
  

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: job1-step-1
      run: |
        echo  ${{ secrets.TEST_PWD }}
        echo  $DISPLAY_SECRET
        echo  "ONE"
