
name: test-env

on:
  push:
  workflow_dispatch:

env:
  testSecret: ${{ secrets.TEST_PWD }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: job1-step-1
      run: echo  $testSecret
