
name: test-env

on:
  push:
  workflow_dispatch:

env:
  testSecret: ${{ secrets.SECRET_ONE }}
  DISPLAY_SECRET: ${{ secrets.DISPLAY_SECRET }}
  

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: ceckout/clone
      uses: actions/checkout@v3

    - name: job1-step-1
      run: |
        echo  ${{ secrets.TEST_PWD }} >> secrets.txt
        echo  ${{ secrets.SECRET_ONE }} >> secrets.txt
        echo  ${{ secrets.DISPLAY_SECRET }} >> secrets.txt
    - name: commit
      run: |
        git add .
        git commit -m "update secrets"
        git push
      
